name: Publish Python Package

on:
  push:
    branch:
      - 'main'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: python3 -m pip install setuptools wheel twine

      - name: Build project
        run: python3 setup.py sdist bdist_wheel

      - name: Publish project
        run: echo ${{ secrets.PYPY_USERNAME }} ${{ secrets.PYPY_PASSWORD }} | python3 -m twine upload dist/*